trigger:
- main

pool:
  vmImage: ubuntu-latest

resources:
 repositories:
   - repository: HISE
     type: github
     name: johnmannix/HISE
     endpoint: johnmannix
     ref: azure-pipelines

variables:
- group: Secrets

stages:
- template: ci/pipeline-template.yml@HISE
  parameters:
    projectFolder: 'smear-campaign'
    pluginFilename: 'Smear Campaign'
